quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Configure auth token lifespan(in seconds)
smallrye.jwt.new-token.lifespan=3600