quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Configure auth token lifespan(in seconds)
smallrye.jwt.new-token.lifespan=3600

# JWT config
smallrye.jwt.sign.key.location=classpath:devTestPrivateKey.pem
mp.jwt.verify.publickey.location=classpath:devTestPublicKey.pem
mp.jwt.verify.issuer=https://quarkus.io/issuer

quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG